### ISSUE TITLE
Deckbuilder search bar: filter "o" doesn't work

### ISSUE THREAD

**Issue by olivierkes** [Sydtrack/ringsdb#40] opened 2016-11-17 21:00 UTC
Searching for "o:1" in the deckbuilder search bar returns nothing, instead of filtering cards whose cost is 1.

**Comment by dkaygithub** [comment] 2017-02-06 21:16
duplicate of [This bug](https://github.com/Sydtrack/ringsdb/issues/11)
Should close this one

**Closed** 2017-02-26 10:16 UTC
